TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
# ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

LIBRARY_IOC = pgpEdt

DBD        += pgpEdtSupport.dbd

LIB_SRCS   += pgpEdt.cpp
LIB_SRCS   += pgpEdtSerial.cpp


include $(ADCORE)/ADApp/commonLibraryMakefile

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
# ADD RULES AFTER THIS LINE

